# Generated by Django 3.1 on 2020-08-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wordKorean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=30)),
                ('acronym', models.CharField(default=None, max_length=20)),
                ('note', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='wordEnglish',
            fields=[
                ('wordkorean', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dict.wordkorean')),
                ('term', models.CharField(max_length=30)),
                ('acronym', models.CharField(default=None, max_length=20)),
                ('note', models.TextField(max_length=500)),
            ],
        ),
    ]
