# Generated by Django 3.1 on 2020-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20200904_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='term',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='translated',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
