version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    networks:
      - nginx_network
      - dict_database_network   
    depends_on:  
      - dict_database

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static   
      - media_volume:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  dict_database:   
    image: postgres:10
    env_file:   
      - config/db/dict_database_env
    networks:   
      - dict_database_network
    volumes:
      - dict_database_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  dict_database_network:   
    driver: bridge

volumes:
  dict_database_volume:
  static_volume:  # <-- declare the static volume
  media_volume:
